

ATK_MULTIPLIER = 2
DEF_MULTIPLIER = 0.5
SHIELD_MULTIPLIER=2
SKL_MULTIPLIER = 1
SKL_RESIST_MULTIPLIER = 1
SKL_DEF_MULTIPLIER = 0.5
SKL_ATK_MULTIPLIER = 2

HP_MULTIPLIER = 10
MP_MULTIPLIER = 3

VARIABILITY = 0.10
